# Generated by Django 4.2.7 on 2023-12-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_pre_marke_prom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pre_marke_prom',
            field=models.FloatField(default=0),
        ),
    ]
