# Generated by Django 4.2.7 on 2023-11-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='total',
            new_name='preco_t',
        ),
    ]
